### ISSUE TITLE
There occured an error when I 

### ISSUE THREAD

**Issue by kuixing233** [lloongx/SFDA-CBMT#4]
![image](https://github.com/lloongx/SFDA-CBMT/assets/48555989/38798039-bf2e-440b-b7ee-134ecacee801)
Trace back is shown in the picture, I want to know how to solve this problem.
May it because the version of some pickages wrong? Can u provided the "requirements.txt"? Thank you!

**Comment by lloongx** [comment]
You can refer to this [link](https://github.com/lloongx/SFDA-CBMT/issues/3#issuecomment-1991391337).

**Comment by kuixing233** [comment]
降低一下numpy版本可以了，感谢🙇‍！
