### ISSUE TITLE
How to obtain a segmented fundus image

### ISSUE THREAD

**Issue by cxuanxiao** [lloongx/SFDA-CBMT#5]
Hello, I'm a beginner. The result I output is quantitative results including Dice and ASSD,but I don't know how to obtain visualized picture.

**Comment by cxuanxiao** [comment]
Looking forward to your reply

**Comment by lloongx** [comment]
It's easy to modify the `eval()` function to visualize images and results with `PIL.Image`.
I do inplement this but it's hard to find the code, so you need to inplement it by yourself :(

**Comment by cxuanxiao** [comment]
I'll try it,thank you!
