### ISSUE TITLE
你好，为什么每次训练过程都是cup类正常，而dice类效果越训练效果越差呢

### ISSUE THREAD

**Issue by kuixing233** [lloongx/SFDA-CBMT#6]
下面是我在本地训练的过程，cup类的dice是增加的，assd是减少的，但disc类反过来了，这是为什么呢，是我有地方弄错了吗，源模型是下载的作者提供的，适应到Domain2和Domain1都是这样

C:\Software\anaconda3\envs\py39\python.exe C:\Users\26090\Downloads\Documents\论文\其他\0511\SFDA-CBMT_miccai2023\SFDA-CBMT-main\train_target.py 
Datasets/Fundus/Domain1/train/ROIs/image
Number of images in train/ROIs: 50
Datasets/Fundus/Domain1/train/ROIs/image
Number of images in train/ROIs: 50
Datasets/Fundus/Domain1/test/ROIs/image
Number of images in test/ROIs: 51
==> Loading DeepLab model file: ./logs_train/Domain3/source_model.pth.tar
initial dice: cup: 0.8492+-0.1250 disc: 0.9650+-0.0162 avg: 0.9071, assd: cup: 10.1034+-6.6718 disc: 4.0247+-1.8986 avg: 7.0640

epoch 1/20:
teacher dice: cup: 0.8233+-0.1168 disc: 0.9566+-0.0206 avg: 0.8900, assd: cup: 11.9825+-6.8035 disc: 5.4279+-3.5248 avg: 8.7052
student dice: cup: 0.8524+-0.1161 disc: 0.9585+-0.0184 avg: 0.9055, assd: cup: 10.0362+-5.6120 disc: 4.7755+-2.1522 avg: 7.4059

epoch 2/20:
teacher dice: cup: 0.8291+-0.1211 disc: 0.9622+-0.0157 avg: 0.8957, assd: cup: 11.6564+-6.8675 disc: 4.3562+-1.8377 avg: 8.0063
student dice: cup: 0.8376+-0.1133 disc: 0.9671+-0.0134 avg: 0.9023, assd: cup: 10.9454+-6.0749 disc: 3.7771+-1.5476 avg: 7.3612

epoch 3/20:
teacher dice: cup: 0.8314+-0.1171 disc: 0.9659+-0.0141 avg: 0.8987, assd: cup: 11.4720+-6.5569 disc: 3.9098+-1.6263 avg: 7.6909
student dice: cup: 0.8337+-0.1116 disc: 0.9653+-0.0141 avg: 0.8995, assd: cup: 11.3448+-6.1757 disc: 3.9328+-1.5564 avg: 7.6388

epoch 4/20:
teacher dice: cup: 0.8514+-0.1175 disc: 0.9678+-0.0134 avg: 0.9096, assd: cup: 10.0911+-6.2266 disc: 3.6729+-1.5391 avg: 6.8820
student dice: cup: 0.8351+-0.1221 disc: 0.9686+-0.0115 avg: 0.9018, assd: cup: 11.2495+-6.8349 disc: 3.5249+-1.2386 avg: 7.3872

epoch 5/20:
teacher dice: cup: 0.8588+-0.1155 disc: 0.9685+-0.0119 avg: 0.9136, assd: cup: 9.5577+-5.8316 disc: 3.5676+-1.3312 avg: 6.5627
student dice: cup: 0.8442+-0.1130 disc: 0.9651+-0.0128 avg: 0.9046, assd: cup: 10.5827+-6.0258 disc: 3.9088+-1.3221 avg: 7.2457

epoch 6/20:
teacher dice: cup: 0.8596+-0.1126 disc: 0.9667+-0.0121 avg: 0.9131, assd: cup: 9.4920+-5.5966 disc: 3.7438+-1.2784 avg: 6.6179
student dice: cup: 0.8571+-0.1129 disc: 0.9648+-0.0134 avg: 0.9110, assd: cup: 9.6454+-5.7778 disc: 3.9234+-1.3432 avg: 6.7844

epoch 7/20:
teacher dice: cup: 0.8570+-0.1123 disc: 0.9661+-0.0122 avg: 0.9115, assd: cup: 9.6908+-5.7000 disc: 3.7942+-1.2666 avg: 6.7425
student dice: cup: 0.8681+-0.1076 disc: 0.9642+-0.0144 avg: 0.9162, assd: cup: 8.8402+-4.9438 disc: 3.9646+-1.4376 avg: 6.4024

epoch 8/20:
teacher dice: cup: 0.8629+-0.1096 disc: 0.9643+-0.0131 avg: 0.9136, assd: cup: 9.2318+-5.2124 disc: 3.9610+-1.3092 avg: 6.5964
student dice: cup: 0.8533+-0.1079 disc: 0.9536+-0.0180 avg: 0.9035, assd: cup: 9.9342+-5.3450 disc: 5.0800+-1.7366 avg: 7.5071

epoch 9/20:
teacher dice: cup: 0.8596+-0.1092 disc: 0.9624+-0.0141 avg: 0.9110, assd: cup: 9.4776+-5.2853 disc: 4.1659+-1.3853 avg: 6.8217
student dice: cup: 0.8681+-0.1084 disc: 0.9604+-0.0175 avg: 0.9143, assd: cup: 8.8982+-5.0978 disc: 4.3550+-1.7207 avg: 6.6266

epoch 10/20:
teacher dice: cup: 0.8670+-0.1077 disc: 0.9592+-0.0160 avg: 0.9131, assd: cup: 8.9176+-4.9169 disc: 4.4941+-1.5431 avg: 6.7058
student dice: cup: 0.8674+-0.1072 disc: 0.9555+-0.0182 avg: 0.9114, assd: cup: 8.8873+-5.0200 disc: 4.8752+-1.7480 avg: 6.8812

epoch 11/20:
teacher dice: cup: 0.8652+-0.1070 disc: 0.9559+-0.0168 avg: 0.9105, assd: cup: 9.0522+-4.9080 disc: 4.8321+-1.6061 avg: 6.9421
student dice: cup: 0.8625+-0.1079 disc: 0.9514+-0.0190 avg: 0.9070, assd: cup: 9.2469+-5.0845 disc: 5.2978+-1.8162 avg: 7.2723

epoch 12/20:
teacher dice: cup: 0.8692+-0.1082 disc: 0.9552+-0.0175 avg: 0.9122, assd: cup: 8.7374+-4.7306 disc: 4.9029+-1.6791 avg: 6.8202
student dice: cup: 0.8687+-0.1089 disc: 0.9512+-0.0211 avg: 0.9099, assd: cup: 8.8062+-4.9133 disc: 5.3135+-2.0349 avg: 7.0598

epoch 13/20:
teacher dice: cup: 0.8684+-0.1089 disc: 0.9537+-0.0183 avg: 0.9111, assd: cup: 8.7990+-4.8238 disc: 5.0587+-1.7656 avg: 6.9288
student dice: cup: 0.8718+-0.1090 disc: 0.9484+-0.0213 avg: 0.9101, assd: cup: 8.5529+-4.7795 disc: 5.6040+-2.0346 avg: 7.0785

epoch 14/20:
teacher dice: cup: 0.8691+-0.1071 disc: 0.9494+-0.0207 avg: 0.9092, assd: cup: 8.7458+-4.6359 disc: 5.5101+-1.9866 avg: 7.1279
student dice: cup: 0.8721+-0.1096 disc: 0.9481+-0.0207 avg: 0.9101, assd: cup: 8.5497+-4.7940 disc: 5.6413+-1.9806 avg: 7.0955

epoch 15/20:
teacher dice: cup: 0.8721+-0.1091 disc: 0.9487+-0.0202 avg: 0.9104, assd: cup: 8.5314+-4.5878 disc: 5.5859+-1.9442 avg: 7.0587
student dice: cup: 0.8737+-0.1120 disc: 0.9470+-0.0208 avg: 0.9103, assd: cup: 8.4322+-4.7628 disc: 5.7579+-1.9793 avg: 7.0951

epoch 16/20:
teacher dice: cup: 0.8728+-0.1094 disc: 0.9457+-0.0212 avg: 0.9093, assd: cup: 8.4907+-4.6075 disc: 5.8878+-2.0118 avg: 7.1893
student dice: cup: 0.8772+-0.1113 disc: 0.9452+-0.0212 avg: 0.9112, assd: cup: 8.1862+-4.6936 disc: 5.9457+-2.0130 avg: 7.0659

epoch 17/20:
teacher dice: cup: 0.8732+-0.1087 disc: 0.9410+-0.0229 avg: 0.9071, assd: cup: 8.4528+-4.5134 disc: 6.3825+-2.1732 avg: 7.4176
student dice: cup: 0.8729+-0.1101 disc: 0.9387+-0.0237 avg: 0.9058, assd: cup: 8.4856+-4.6768 disc: 6.6249+-2.2333 avg: 7.5553

epoch 18/20:
teacher dice: cup: 0.8701+-0.1065 disc: 0.9389+-0.0246 avg: 0.9045, assd: cup: 8.6790+-4.5551 disc: 6.6001+-2.3553 avg: 7.6396
student dice: cup: 0.8723+-0.1084 disc: 0.9349+-0.0262 avg: 0.9036, assd: cup: 8.5359+-4.7022 disc: 7.0186+-2.4921 avg: 7.7772

epoch 19/20:
teacher dice: cup: 0.8715+-0.1071 disc: 0.9362+-0.0250 avg: 0.9038, assd: cup: 8.5899+-4.4947 disc: 6.8827+-2.3824 avg: 7.7363
student dice: cup: 0.8746+-0.1093 disc: 0.9344+-0.0253 avg: 0.9045, assd: cup: 8.3487+-4.6863 disc: 7.0773+-2.3909 avg: 7.7130

epoch 20/20:
teacher dice: cup: 0.8740+-0.1098 disc: 0.9334+-0.0256 avg: 0.9037, assd: cup: 8.4033+-4.5020 disc: 7.1774+-2.4270 avg: 7.7903
student dice: cup: 0.8746+-0.1111 disc: 0.9337+-0.0259 avg: 0.9042, assd: cup: 8.3609+-4.7493 disc: 7.1514+-2.4646 avg: 7.7561

Process finished with exit code 0

**Comment by lloongx** [comment]
It may be due to environmental differences; you may need to tune the hyper-parameters to find the best ones for your case.

**Comment by kuixing233** [comment]
在服务器上训练正常了，感谢回复🙇‍
