### ISSUE TITLE
Visualization result implementation

### ISSUE THREAD

**Issue by H-CODE6** [lloongx/SFDA-CBMT#8]
Dear author, thank you very much for opening up this project. We are very interested in it and have conducted experiments to reproduce it. However, we found that no visualization results were generated in the end. Could you please open source this part of the code in your spare time for us to further learn and refer to? Thank you very much, looking forward to your reply!

**Comment by lloongx** [comment]
Since we mainly focus on quantitative results, we didn't implement any visualization codes.

Feature visualization methods like [t-SNE](https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html) should be easy to implement, you can have a try.

**Comment by lloongx** [comment]
Visualization of segmentation results can be easily generated by `torchvision.utils.save_image` from model output tensors. You can have a try.

**Comment by H-CODE6** [comment]
Thank you very much for your reply. Would it be convenient for you to synchronize and update the source code or operations for visualizing this part? This can help us to have a deeper understanding of learning. Looking forward to your reply

**Comment by lloongx** [comment]
I didn't keep the original code in my current PC.
I think the visualization operation is quite basic. You can even ask ChatGPT to do this.
So please do it yourself :)
